version: "3.7"
services:
  tr_php:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: transactions-local
    container_name: transactions-local-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - transactions-local
  tr_nginx:
    image: nginx:1.17-alpine
    container_name: transactions-local-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - transactions-local

networks:
  transactions-local:
    driver: bridge

