controllers_common:
    resource: ../../src/Infrastructure/Common/Controller/
    type: attribute

controllers_transactions:
    resource: ../../src/Infrastructure/Transactions/Controller/
    type: attribute

kernel:
    resource: ../../src/Infrastructure/Kernel.php
    type: attribute
