controllers_common:
    resource: ../../src/Infrastructure/Common/Controller/
    type: annotation

controllers_transactions:
    resource: ../../src/Infrastructure/Transactions/Controller/
    type: annotation

kernel:
    resource: ../../src/Infrastructure/Kernel.php
    type: annotation
